spring:
  application:
    name: ricky-mall
  main:
    allow-circular-references: true
  profiles:
    active: dev
  datasource:
    driver-class-name: ${datasource.driver-class-name}
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${datasource.username}
    password: ${datasource.password}
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

mybatis-plus:
  type-aliases-package: com.ricky.persistence.po
  global-config:
    db-config:
      id-type: auto
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

## Dubbo
#dubbo:
#  application:
#    name: xfg-frame-dev
#    version: 1.0.0
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  protocol:
#    name: dubbo
#    port: 20883
#  scan:
#    base-packages: cn.bugstack.xfg.frame.api

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 200
        keep-alive-time: 10
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 限流配置
rate-limiter:
  permits-per-second: 1
  timeout: 5

jwt:
  secret-key: ${this.jwt.secret-key}
  ttl: ${this.jwt.ttl}
  token-name: ${this.jwt.token-name}

aggregate-cache:
  # 缓存DDD聚合前缀id，防止redis存储对象的名字一致时，对数据进行覆盖，仅redis有效
  appName: ricky_mall
  # 可选---  map caffeine redis
  type: caffeine
  # 过期时间，单位 毫秒
  cacheExpiresTime: 240000
  # 最大容量，该属性仅对本地缓存有效
  cacheExpiresSize: 10000

# Knife4j文档
knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  openapi:
    title: ricky-mall接口文档
    description: "ricky-mall接口文档"
    email: 10449469060@qq.com
    version: 0.0.1-SNAPSHOT
    license: Apache 2.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ricky.trigger.http
